In [1]:
import pandas as pd
import tweepy
import datetime as DT
import re

In [2]:
# Client Tokens and Keys
bearer_token = 'AAAAAAAAAAAAAAAAAAAAAH8BeQEAAAAAqHZLKpw6kolU1Qp9Yt5QQ3rTwcQ%3DNHcfn7XkEjrJgYR5mxow3GP4LOghK8cfIUyaFETwgjNBVvwBJR'
consumer_key = 'WBmtgdzuflK4fWKS0qeUjqCew'
consumer_secret = 'Eds4iM7rqSXBrP5llwiQ8yeKePzvy8u8W7t4k5bJUPT09LZC5B'
access_token = '1541825634648723457-98HEAoF6UI21NC2WxCRnxpxAsc1c7C'
access_token_secret = 'qyjqTI0NtsPLR1Tr86cYbtBIZ1JjSAmSwyGOojHpjgH94'

# Initializing the client
client = tweepy.Client(
    bearer_token = bearer_token,
    consumer_key = consumer_key,
    consumer_secret = consumer_secret,
    access_token = access_token,
    access_token_secret = access_token_secret,
    wait_on_rate_limit = True
)

In [3]:
# Query to search for tweets
query = '(\"boot barn\" OR \"bootbarn\") -is:retweet'

#Search the past seven days for tweets that include the words boot barn or bootbarn
tweet_paginator = tweepy.Paginator(
    client.search_recent_tweets,
    query = query, 
    expansions = 'author_id',
    max_results = 100,
    tweet_fields = ["created_at", "text", "public_metrics"],
    user_fields = ["name", "username", "location", "verified"]
)

In [4]:
tweets = []
users = []

for tweet_page in tweet_paginator:
    tweets += tweet_page.data
    users += tweet_page.includes["users"]

In [5]:
# Shows how many tweets there are and how many unique users tweeted
# print(len(tweets))
# print(len(users))

121
109

In [6]:
# Data frame for tweet metrics
text_df = pd.DataFrame.from_dict(tweets)
# text_df.head(10)

,author_id,created_at,id,public_metrics,text
0,121158213,2022-07-18 17:06:37+00:00,1549078198301782018,"{'retweet_count': 0, 'reply_count': 0, 'like_c...","REVERSALtoUP: $BOOT Boot Barn Holdings, Inc. üì≥..."
1,1475915681887571974,2022-07-18 16:50:16+00:00,1549074083211608064,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",Chart of the Moment:\n\r$BOOT Boot Barn Holdin...
2,33575126,2022-07-18 06:41:00+00:00,1548920757337460736,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",@tradesmanmoney @bootbarn look good
3,1557410246,2022-07-18 06:24:19+00:00,1548916556624584704,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",i need me a trip to boot barn asap
4,235355170,2022-07-18 03:24:11+00:00,1548871223844737026,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",Can‚Äôt wait until boot barn opens ü´∂üèº
5,180140399,2022-07-18 02:57:06+00:00,1548864408193011714,"{'retweet_count': 0, 'reply_count': 1, 'like_c...",@rhinotary If you‚Äôre fully decked out in the l...
6,1380288958190428160,2022-07-18 01:44:18+00:00,1548846088236412928,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",Exit 285 between LMF Horse Feeds and the Boot ...
7,3306537860,2022-07-17 22:12:06+00:00,1548792688106803200,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",@rio_gan1 Bruh Boot Barn packed asf rn üò§
8,1446225619595972609,2022-07-17 21:55:03+00:00,1548788397677879296,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",@Cowboy_Larrie YESSSS get you a pair!! i got m...
9,151592894,2022-07-17 20:18:14+00:00,1548764033553235968,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",I‚Äôm here to say- I guess I‚Äôm a boot barn gal.

In [7]:
text_df[['retweet_count', 'reply_count', 'like_count', 'quote_count']] = pd.DataFrame(text_df.public_metrics.tolist(), 
                                                                                      index = text_df.index)
text_df = text_df.drop(['public_metrics'], axis = 1)

In [8]:
# text_df.head(10)

,author_id,created_at,id,text,retweet_count,reply_count,like_count,quote_count
0,121158213,2022-07-18 17:06:37+00:00,1549078198301782018,"REVERSALtoUP: $BOOT Boot Barn Holdings, Inc. üì≥...",0,0,0,0
1,1475915681887571974,2022-07-18 16:50:16+00:00,1549074083211608064,Chart of the Moment:\n\r$BOOT Boot Barn Holdin...,0,0,0,0
2,33575126,2022-07-18 06:41:00+00:00,1548920757337460736,@tradesmanmoney @bootbarn look good,0,0,1,0
3,1557410246,2022-07-18 06:24:19+00:00,1548916556624584704,i need me a trip to boot barn asap,0,0,0,0
4,235355170,2022-07-18 03:24:11+00:00,1548871223844737026,Can‚Äôt wait until boot barn opens ü´∂üèº,0,0,0,0
5,180140399,2022-07-18 02:57:06+00:00,1548864408193011714,@rhinotary If you‚Äôre fully decked out in the l...,0,1,1,0
6,1380288958190428160,2022-07-18 01:44:18+00:00,1548846088236412928,Exit 285 between LMF Horse Feeds and the Boot ...,0,0,0,0
7,3306537860,2022-07-17 22:12:06+00:00,1548792688106803200,@rio_gan1 Bruh Boot Barn packed asf rn üò§,0,0,0,0
8,1446225619595972609,2022-07-17 21:55:03+00:00,1548788397677879296,@Cowboy_Larrie YESSSS get you a pair!! i got m...,0,0,1,0
9,151592894,2022-07-17 20:18:14+00:00,1548764033553235968,I‚Äôm here to say- I guess I‚Äôm a boot barn gal.,0,0,1,0

In [9]:
for i in range(len(text_df['text'])):
    text_df.iloc[i, 3] = re.sub(r'https\S+', '', text_df['text'][i])

In [12]:
# Testing for duplicates
# (text_df["id"]).is_unique

In [13]:
# Data frame for user metrics
user_df = pd.DataFrame.from_dict(users)
user_df = user_df.rename(columns = {'id': 'author_id'})
# user_df.head()

In [14]:
# Number of unique users this week
user_count = len(user_df['author_id'])

In [15]:
# Creating empty lists for follower and following count to add to result data frame
follower_count = [0] * user_count
following_count = [0] * user_count

In [16]:
# Looping through all users and running get_users endpoint to get the number of followers and following
for i in range(user_count):
    user_metrics = client.get_users(ids = user_df['author_id'][i], user_fields = ['public_metrics'])
    follower_count[i] = user_metrics.data[0].public_metrics['followers_count']
    following_count[i] = user_metrics.data[0].public_metrics['following_count']

Rate limit exceeded. Sleeping for 327 seconds.

In [17]:
# Adding new metrics to the user data frame
user_df['follower_count'] = follower_count
user_df['following_count'] = following_count

In [18]:
# Verifying updated user metrics data frame that includes follower and following count
# user_df.head()

In [19]:
# Combining tweet and user metrics into single data frame
result = pd.merge(text_df, user_df)
# result

In [20]:
# Cleaning the data frame to be exported (remove duplicates, reindexing, reordering columns)
result = result.drop_duplicates()
result = result.reset_index()
result = result.drop(columns = 'index')
result = result[['id', 'text', 'created_at', 
                 'retweet_count', 'reply_count', 'like_count', 'quote_count', 
                 'author_id', 'username', 'name', 'follower_count', 'following_count', 
                 'location', 'verified']]
result

,id,text,created_at,retweet_count,reply_count,like_count,quote_count,author_id,username,name,follower_count,following_count,location,verified
0,1549078198301782018,"REVERSALtoUP: $BOOT Boot Barn Holdings, Inc. üì≥...",2022-07-18 17:06:37+00:00,0,0,0,0,121158213,AlertTrade,"Trade Alerts, Trade Ideas and Crypto üá∫üá∏",174187,154507,NaN,False
1,1549074083211608064,Chart of the Moment:\n\r$BOOT Boot Barn Holdin...,2022-07-18 16:50:16+00:00,0,0,0,0,1475915681887571974,marketreaderbot,MarketReader Bot,1758,10,NaN,False
2,1548920757337460736,@tradesmanmoney @bootbarn look good,2022-07-18 06:41:00+00:00,0,0,1,0,33575126,pianoman6398,Brian Randall,970,982,"Portland, Oregon",False
3,1548916556624584704,i need me a trip to boot barn asap,2022-07-18 06:24:19+00:00,0,0,0,0,1557410246,chavandowski,happy real madrid fan,532,263,NaN,False
4,1548871223844737026,Can‚Äôt wait until boot barn opens ü´∂üèº,2022-07-18 03:24:11+00:00,0,0,0,0,235355170,ErikaVirag,ErikaV,1307,587,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,1546645559603335169,@bootbarn @brycetucker3 He seen a pair of ostr...,2022-07-12 00:00:11+00:00,1,1,2,0,1226434428,STACKNAK,Uncle Bucc,813,779,"Lexington, Ky",False
117,1546640244249767938,@shaia_tempari @MuirMJones The bolo tie is wha...,2022-07-11 23:39:04+00:00,0,0,0,0,1124705297614794753,sweet_peajh,PJ,147,788,"Missoula, MT",False
118,1546620296949485570,"@h__th_r Depends on the boot, if I am looking ...",2022-07-11 22:19:48+00:00,0,1,1,0,867488655232819200,MajorGrunge,MAJOR GRUNGE,877,642,he/they,False
119,1546584311012347905,the workers at boot barn broooüòç,2022-07-11 19:56:48+00:00,0,1,3,0,1455755132570771458,stephaniie_ee,stephaniee,190,189,NaN,False
120,1546571151941550082,@Podverty You ever been to boot barn?,2022-07-11 19:04:31+00:00,0,1,0,0,1468805047743959044,89AGE24,AGE,283,319,NaN,False

In [21]:
result.to_csv("twitter_feed.csv")